%{
  (* Header section *)
  open Ast
  
  (* Exception for type checking errors, if needed in actions *)
  exception Type_error of string
  
  (* Note: Parser.Error is automatically generated by OCamlyacc/Menhir 
     for syntax errors - we don't need to declare it here *)
  
  (* Helper functions for constructing vector/matrix literals *)
  let make_vector_lit dimension elements =
    VectorLit(dimension, elements)
    
  let make_matrix_lit rows cols rows_list =
    MatrixLit(rows, cols, rows_list)
%}

(* Token declarations (must match tokens.mli ) *)
%token <bool> BOOL_LITERAL
%token <int> INT_POS_LITERAL
%token <float> FLOAT_LITERAL
%token <string> STRING_LITERAL
%token <string> ID

(* Keywords *)
%token INPUT PRINT
%token BOOL INT FLOAT VECTOR MATRIX
%token IF THEN ELSE
%token FOR WHILE DO
%token TRUE FALSE
%token AND OR NOT XOR
%token DOT MAG DIM ANGLE TRANS DET ABS

(* Operators and punctuation *)
%token PLUS MINUS MUL DIV MOD
%token EQ NEQ LT GT LEQ GEQ
%token ASSIGN
%token SEMICOLON COMMA
%token LPAREN RPAREN
%token LBRACE RBRACE
%token LBRACKET RBRACKET
%token EOF

(* Operator precedence *)
%nonassoc SEMICOLON
%nonassoc ELSE
%nonassoc ASSIGN
%left OR
%left AND
%left XOR
%left EQ NEQ
%left LT GT LEQ GEQ
%left PLUS MINUS
%left MUL DIV MOD
%nonassoc NOT
%nonassoc UMINUS
%nonassoc DOT MAG DIM ANGLE TRANS DET ABS

(* Entry point *)
%start program
%type <Ast.program> program

%%
(* Grammar rules *)

program:
  stmt_list EOF { Program($1) }
  ;

stmt_list:
  /* empty */ { [] }
| stmt stmt_list { $1 :: $2 }
  ;

stmt:
  expr SEMICOLON                                            { ExprStmt($1) }
| BOOL ID SEMICOLON                                         { DeclStmt($2, BoolType, None) }
| INT ID SEMICOLON                                          { DeclStmt($2, IntType, None) }
| FLOAT ID SEMICOLON                                        { DeclStmt($2, FloatType, None) }
| VECTOR ID SEMICOLON                                       { DeclStmt($2, VectorType(None), None) }
| MATRIX ID SEMICOLON                                       { DeclStmt($2, MatrixType(None, None), None) }
| BOOL ID ASSIGN expr SEMICOLON                             { DeclStmt($2, BoolType, Some $4) }
| INT ID ASSIGN expr SEMICOLON                              { DeclStmt($2, IntType, Some $4) }
| FLOAT ID ASSIGN expr SEMICOLON                            { DeclStmt($2, FloatType, Some $4) }
| VECTOR ID ASSIGN expr SEMICOLON                           { DeclStmt($2, VectorType(None), Some $4) }
| MATRIX ID ASSIGN expr SEMICOLON                           { DeclStmt($2, MatrixType(None, None), Some $4) }
| ID ASSIGN expr SEMICOLON                                  { AssignStmt($1, $3) }
| IF LPAREN expr RPAREN block_stmt                          { IfStmt($3, $5, None) }
| IF LPAREN expr RPAREN block_stmt ELSE block_stmt          { IfStmt($3, $5, Some $7) }
| FOR LPAREN expr SEMICOLON expr SEMICOLON expr RPAREN block_stmt
                                                            { ForStmt($3, $5, $7, $9) }
| WHILE LPAREN expr RPAREN block_stmt                       { WhileStmt($3, $5) }
| DO block_stmt WHILE LPAREN expr RPAREN SEMICOLON          { DoWhileStmt($2, $5) }
  ;

block_stmt:
  LBRACE stmt_list RBRACE                                     { Block($2) }
  ;

expr:
  literal                                                   { $1 }
| ID                                                         { Var($1) }
| INPUT LPAREN RPAREN                                        { Input(None) }
| INPUT LPAREN expr RPAREN                                   { Input(Some $3) }
| PRINT LPAREN expr RPAREN                                   { Print($3) }
| LPAREN expr RPAREN                                         { $2 }
| NOT expr                                                  { NOT($2) }
| MINUS expr %prec UMINUS                                    { NEG($2) }
| expr PLUS expr                                             { PLUS($1, $3) }
| expr MINUS expr                                            { MINUS($1, $3) }
| expr MUL expr                                              { TIMES($1, $3) }
| expr DIV expr                                              { DIV($1, $3) }
| expr MOD expr                                              { MOD($1, $3) }
| expr AND expr                                              { AND($1, $3) }
| expr OR expr                                               { OR($1, $3) }
| expr XOR expr                                              { XOR($1, $3) }
| expr EQ expr                                               { EQ($1, $3) }
| expr NEQ expr                                              { NEQ($1, $3) }
| expr LT expr                                               { LT($1, $3) }
| expr GT expr                                               { GT($1, $3) }
| expr LEQ expr                                              { LEQ($1, $3) }
| expr GEQ expr                                              { GEQ($1, $3) }
| DOT expr expr                                              { DOT($2, $3) }
| ID ASSIGN expr                                             { Assign($1, $3) }
| ABS LPAREN expr RPAREN                                     { ABS($3) }
| MAG expr                                                   { MAG($2) }
| DIM expr                                                   { DIM($2) }
| ANGLE expr expr                                            { ANGLE($2, $3) }
| TRANS expr                                                 { TRANS($2) }
| DET expr                                                   { DET($2) }
| vector_construction                                        { $1 }
| matrix_construction                                        { $1 }
  ;

vector_construction:
  INT_POS_LITERAL vector_lit                                     { make_vector_lit (Some $1) $2 }
  ;

matrix_construction:
  INT_POS_LITERAL COMMA INT_POS_LITERAL matrix_lit                   { make_matrix_lit (Some $1) (Some $3) $4 }
  ;

literal:
  BOOL_LITERAL                                               { BoolLit($1) }
| INT_POS_LITERAL                                                { IntLit($1) }
| FLOAT_LITERAL                                              { FloatLit($1) }
| STRING_LITERAL                                             { StringLit($1) }
| vector_lit                                                 { VectorLit(None, $1) }
| matrix_lit                                                 { MatrixLit(None, None, $1) }
  ;

vector_lit:
  LBRACKET expr_list RBRACKET                                  { $2 }
  ;

matrix_lit:
  LBRACKET row_list RBRACKET                                   { $2 }
  ;

row_list:
  vector_lit                                                 { [$1] }
| vector_lit COMMA row_list                                  { $1 :: $3 }
  ;

expr_list:
  /* empty */                                                { [] }
| non_empty_expr_list                                        { $1 }
  ;

non_empty_expr_list:
  expr                                                       { [$1] }
| expr COMMA non_empty_expr_list                             { $1 :: $3 }

  ;
%%
